/**
 * 06 — PostgreSQL: the same id contract on the database side.
 *
 * This example prints the SQL rather than connecting, so it runs anywhere.
 * To apply it for real: `npx entity-id sql | psql "$DATABASE_URL"`.
 *
 * Run: `npx tsx examples/06-postgres.ts`
 */
import {
  ENTITY_ID_SQL,
  entityIdCheckSql,
  entityIdColumnSql,
  entityIdDefaultSql,
} from 'entity-id/sql';

// One column definition that both generates and enforces the contract.
console.log('[a table using entity ids]');
console.log(`create table users (
  ${entityIdColumnSql('usr')},
  email text not null unique,
  created_at timestamptz not null default now()
);`);

console.log(`\ncreate table orders (
  ${entityIdColumnSql('ord')},
  user_id text not null references users(id),
  -- A foreign key can carry its own prefix check, so a user id cannot be
  -- stored in a column meant for orders.
  check (${entityIdCheckSql('user_id', 'usr')})
);`);

// The pieces are available separately, for an existing table.
console.log('\n[adding the contract to an existing column]');
console.log(`alter table legacy_items
  alter column id set default ${entityIdDefaultSql('itm')},
  add constraint legacy_items_id_check check (${entityIdCheckSql('id', 'itm')});`);

// The migration itself installs three functions.
console.log('\n[what the migration installs]');
for (const line of ENTITY_ID_SQL.split('\n')) {
  const match = /^create or replace function (public\.\w+)/.exec(line);
  if (match) console.log('  ', match[1]);
}

console.log(`
Ids generated by public.entity_id_generate() satisfy this package's validators,
and ids minted here satisfy the SQL CHECK — the two are cross-checked against a
real PostgreSQL instance by scripts/verify-sql-crosscheck.sh.`);
